gui_files = [
	'bookentry.cc',
	'dialogentry.cc',
	'downloadqueue.cc',
	'entry.cc',
	'favoritehubs.cc',
	'finishedtransfers.cc',
	'hashdialog.cc',
	'hub.cc',
	'mainwindow.cc',
#SSP: Adding fblauncher source file.
	'fblauncher.cc',
	'privatemessage.cc',
	'publichubs.cc',
	'search.cc',
	'settingsdialog.cc',
	'settingsmanager.cc',
	'sharebrowser.cc',
	'treeview.cc',
	'UserCommandMenu.cc',
	'wulfor.cc',
	'wulformanager.cc',
	'WulforUtil.cc']

Import('env')

# Get the cflags. We copy the env since so we don't want to add these flags globally (scons bug?)
env_gui = env.Clone()
env_gui.ParseConfig('pkg-config --cflags libglade-2.0')

# Build the gui_files
guiObjs = env_gui.Object(gui_files)

Return('guiObjs')
